trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  GOMODCACHE: $(Agent.HomeDirectory)/gomodcache

steps:
  - task: Cache@2
    inputs:
      key: '"gomod" | "$(Agent.OS)" | go.sum'
      restoreKeys: |
        gomod | "$(Agent.OS)"
      path: $(GOMODCACHE)
    displayName: Cache Go Mod Cache
  - task: GoTool@0
    inputs:
      version: "1.16.7"
  - template: templates/go-build.yml
    parameters:
      bin: spl
      version: $(RELEASE_VERSION)

  - task: GitHubRelease@1
    displayName: "Remove Exist GitHub Release"
    continueOnError: true
    inputs:
      gitHubConnection: spl
      action: delete
      tag: "v$(RELEASE_VERSION)"
  - task: GitHubRelease@1
    displayName: "GitHub Release"
    inputs:
      gitHubConnection: spl
      action: edit
      tag: "v$(RELEASE_VERSION)"
      title: "v$(RELEASE_VERSION)"
      assets: "$(System.DefaultWorkingDirectory)/release/*"
      isDraft: true
      addChangeLog: false
