trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: GoTool@0
    inputs:
      version: "1.16.7"
  - template: templates/go-build.yml
    parameters:
      bin: spl
      version: $(RELEASE_VERSION)
  - task: GitHubRelease@1
    displayName: "GitHub Release"
    inputs:
      gitHubConnection: spl
      action: edit
      tag: "v$(RELEASE_VERSION)"
      assets: "$(System.DefaultWorkingDirectory)/release/*"
      isDraft: true
      addChangeLog: false
