trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  GOMODCACHE: $(Agent.HomeDirectory)/gomodcache

steps:
  - task: Cache@2
    inputs:
      key: '"gomod" | "$(Agent.OS)" | go.sum'
      restoreKeys: |
        gomod | "$(Agent.OS)"
      path: $(GOMODCACHE)
    displayName: Cache Go Mod Cache
  - task: GoTool@0
    inputs:
      version: "1.16.7"
  - task: Go@0
    inputs:
      command: build
      arguments: '-ldflags "-X main.CliVersion=FAKE" .'
  - script: ./spl -v
    displayName: Test ldflags
  - script: |
      echo 'Current directory is {{ env "PWD" }}, value of `foo` is {{ .foo }}.' | ./spl --var 'foo=bar'
    displayName: Test template
