trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: GoTool@0
    inputs:
      version: "1.16.7"
  - script: go build -ldflags '-X main.CliVersion=FAKE' .
    displayName: Build
  - script: ./spl -v
    displayName: Test ldflags
  - script: echo 'Current directory is {{ env "PWD" }}, value of `foo` is {{ .foo }}' | ./spl --var 'foo=bar'
    displayName: Test template
