name: Build Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v .

      - name: Test
        run: echo 'Current Directory is `{{ env "PWD" }}`, input var of `foo` is `{{ .foo }}`' | ./spl -v 'foo=bar'
